object Versions {
    const val kotlin = "1.4.0"
    const val kotlin_coroutines = "1.3.9"
    const val dagger = "2.28.3"
    const val dagger_hilt = "2.28.3-alpha"
    const val dagger_hilt_jetpack = "1.0.0-alpha02"
    const val glide = "4.11.0"
    const val junit = "4.13"
    const val lottie = "3.4.1"
    const val material = "1.2.0"
    const val mockk = "1.10.0"
    const val retrofit = "2.9.0"
    object AndroidX {
        const val appCompat = "1.1.0"
        const val arch_core = "2.1.0"
        const val cardView = "1.0.0"
        const val compose = "1.0.0-alpha01"
        const val constraintLayout = "2.0.0"
        const val core = "1.3.0"
        const val fragment = "1.3.0-alpha08"
        const val lifecycle = "2.3.0-alpha06"
        const val navigation = "2.3.0"
        const val pagination = "3.0.0-alpha05"
        const val test_ext = "1.1.1"
        const val room = "2.2.5"
        const val test_espresso = "3.2.0"
    }
}
