object Versions {
    const val kotlin = "1.4.21-2"
    const val kotlin_coroutines = "1.4.2"
    const val accompanist = "0.5.0"
    const val dagger = "2.31"
    const val dagger_hilt = "2.31-alpha"
    const val glide = "4.11.0"
    const val java_desugar = "1.0.10"
    const val junit = "4.13"
    const val lottie = "3.4.1"
    const val material = "1.2.0"
    const val mockk = "1.10.2"
    const val retrofit = "2.9.0"
    object AndroidX {
        const val appcompat = "1.2.0"
        const val arch_core = "2.1.0"
        const val cardview = "1.0.0"
        const val compose = "1.0.0-alpha11"
        const val constraintLayout = "2.0.0"
        const val core = "1.3.2"
        const val dagger_hilt = "1.0.0-alpha03"
        const val fragment = "1.3.0-beta01"
        const val lifecycle = "2.3.0-beta01"
        const val navigation = "2.3.3"
        const val navigation_compose = "1.0.0-alpha06"
        const val paging = "3.0.0-alpha08"
        const val room = "2.2.5"
        const val test_ext = "1.1.2"
        const val test_espresso = "3.3.0"
    }
}
