object Versions {
    const val kotlin = "1.4.0-rc"
    const val kotlin_coroutines = "1.3.8-1.4.0-rc"
    const val dagger = "2.28.3"
    const val dagger_hilt = "2.28.3-alpha"
    const val dagger_hilt_jetpack = "1.0.0-alpha02"
    const val glide = "4.11.0"
    const val junit = "4.13"
    const val lottie = "3.4.1"
    const val material = "1.2.0"
    const val moshi = "2.7.0"
    object AndroidX {
        const val appCompat = "1.1.0"
        const val cardView = "1.0.0"
        const val compose = "0.1.0-dev16"
        const val constraintLayout = "2.0.0-rc1"
        const val core = "1.3.0"
        const val fragment = "1.2.5"
        const val lifecycle = "2.3.0-alpha06"
        const val navigation = "2.3.0"
        const val pagination = "3.0.0-alpha03"
        const val test_ext = "1.1.1"
        const val test_espresso = "3.2.0"
    }
}
